version: '3'

services:
  sea:
    image: "node:8"
    tty: true
    stdin_open: true
    working_dir: /home/node/app/src
    volumes:
      - ./:/home/node/app
    ports:
      - "4200:4200"
    command: "npm run start"